import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "../../styles/MyCharacter.module.css";
import { useQuery, gql } from "@apollo/client";
import Spinner from "../../components/spinner/spinner";
import { Button } from "@material-ui/core";

export async function getServerSideProps({ params }) {
  //for staticProps params should come from getStaticPaths
  return {
    props: {
      params,
    },
  };
}

export default function MyCharacter(props) {
  const params = props.params;
  const id = params.id.split("-")[1];

  const Character_data = gql`
    query CharacterByIdsQuery($ids: [ID!]!) {
      charactersByIds(ids: $ids) {
        id
        name
        status
        species
        type
        gender
        origin {
          name
        }
        location {
          name
        }
        image
      }
    }
  `;
  const { loading, error, data } = useQuery(Character_data, {
    variables: { ids: id },
  });
  if (loading) return <Spinner />;
  if (error) return <p>Error :(</p>;

  const { name, image, gender, location, origin, species, status } =
    data.charactersByIds[0];
  return (
    <div className={styles.container}>
      <Head>
        <title>Ricky and Morty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.profile}>
          <div className={styles.profile_image}>
            <Image src={image} alt={name} width="300" height="300" />
          </div>
          <div className={styles.profile_details}>
            <h2 className={styles.character_details}>Character Details</h2>
            <div>
              <strong>Name:</strong> {name}
            </div>
            <div>
              <strong>Status:</strong> {status}
            </div>
            <div>
              <strong>Gender:</strong> {gender}
            </div>
            <div>
              <strong>Species:</strong> {species}
            </div>
            <div>
              <strong>Location:</strong> {location.name}
            </div>
            <div>
              <strong>Originally From:</strong> {origin.name}
            </div>
          </div>
        </div>
        <br />
        <br />
        <Button variant="contained" color="primary" size="large">
          <Link href="/">
            <a><strong>Back</strong></a>
          </Link>
        </Button>
      </main>
    </div>
  );
}
