// import Layout from "../../components/layout";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "../../styles/MyCharacter.module.css";
import { useQuery, gql } from "@apollo/client";
// import isHome from "../index.js";

// const defaultEndPoint = `https://rickandmortyapi.com/api/character/`;
export async function getServerSideProps({ params }) {
  //for staticProps params should come from getStaticPaths
  // const id = params.id;
  // const url = defaultEndPoint + id;
  // // console.log(url);
  // const response = await fetch(url);
  // const data = await response.json();
  return {
    props: {
      params,
    },
  };
}
// console.log(isHome);
export default function MyCharacter(props) {
  // console.log(props);
  const params = props.params;
  const id = params.id;

  const Character_data = gql`
    query CharacterByIdsQuery($ids: [ID!]!) {
      charactersByIds(ids: $ids) {
        id
        name
        status
        species
        type
        gender
        origin {
          name
        }
        location {
          name
        }
        image
      }
    }
  `;
  const { loading, error, data } = useQuery(Character_data, {
    variables: { ids: id },
  });
  if (loading) return <p>Loading...</p>;
  if (error) return <p>Error :(</p>;

  const { name, image, gender, location, origin, species, status } =
    data.charactersByIds[0];
  // console.log(data.charactersByIds[0]);
  // console.log(char_id);
  // console.log(name);
  // console.log(image);
  // console.log(gender);
  // console.log(location);
  // console.log(origin);
  // console.log(species);
  // console.log(status);
  // console.log(name);

  return (
    <div className={styles.container}>
      <Head>
        <title>Ricky and Morty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.profile}>
          <div className={styles.profile_image}>
            <Image src={image} alt={name} width="300" height="300" />
          </div>
          <div className={styles.profile_details}>
            <h2 className={styles.character_details}>Character Details</h2>
            <div>
              <strong>Name:</strong> {name}
            </div>
            <div>
              <strong>Status:</strong> {status}
            </div>
            <div>
              <strong>Gender:</strong> {gender}
            </div>
            <div>
              <strong>Species:</strong> {species}
            </div>
            <div>
              <strong>Location:</strong> {location.name}
            </div>
            <div>
              <strong>Originally From:</strong> {origin.name}
            </div>
          </div>
        </div>
        <br />
        <br />
        <p
          className={styles.back}
          onClick={() => {
            console.log("onClick");
          }}
        >
          <Link href="/">
            <a>Back to All Characters</a>
          </Link>
        </p>
      </main>
    </div>
  );
}
