// import Layout from "../../components/layout";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "../../styles/MyCharacter.module.css";

const defaultEndPoint = `https://rickandmortyapi.com/api/character/`;
export async function getServerSideProps({ params }) {
  //for staticProps params should come from getStaticPaths
  const id = params.id;
  const url = defaultEndPoint + id;
  // console.log(url);
  const response = await fetch(url);
  const data = await response.json();
  return {
    props: {
      data,
    },
  };
}

export default function MyCharacter(props) {
  // console.log(props);
  const { name, image, gender, location, origin, species, status } = props.data;
  // console.log(name);
  return (
    <div className={styles.container}>
      <Head>
        <title>Ricky and Morty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.profile}>
          <div className={styles.profile_image}>
            <Image src={image} alt={name} width="300" height="300" />
          </div>
          <div className={styles.profile_details}>
            <h2 className={styles.character_details}>Character Details</h2>
            <div>
              <strong>Name:</strong> {name}
            </div>
            <div>
              <strong>Status:</strong> {status}
            </div>
            <div>
              <strong>Gender:</strong> {gender}
            </div>
            <div>
              <strong>Species:</strong> {species}
            </div>
            <div>
              <strong>Location:</strong> {location.name}
            </div>
            <div>
              <strong>Originally From:</strong> {origin.name}
            </div>
          </div>
        </div>
        <br />
        <br />
        <p className={styles.back}>
          <Link href="/">
            <a>Back to All Characters</a>
          </Link>
        </p>
      </main>
    </div>
  );
}
